###########
# site.title

title:    'Francesco Mari'
subtitle: 'full stack human'
permalink: /notes/:title
#permalink: /:year/:month/:day/:title

nav:
- { title: 'About',                href: '/' }
- { title: 'Projects',             href: '/projects' }
- { title: 'Mographs',             href: '/mographs' }
- { title: 'Interesting things',   href: '/interesting-things' }
- { title: 'Notes',                href: '/notes' }


#########################
# more settings

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
