###########
# site.title

title:    'Francesco Mari'
subtitle: 'full stack human'
permalink: /notes/:title
#permalink: /:year/:month/:day/:title

nav:
- { title: 'About', href: '/' }
- { title: 'Projects', href: '/projects' }
- { title: 'Resume', href: '/assets/pdf/francesco-mari-resume.pdf', target: 'blank' }
- { title: 'Interesting things', href: '/serendipity' }
- { title: 'Mographs', href: '/mographs' }
#- { title: 'Notes',                href: '/notes' }


#########################
# more settings

markdown: kramdown
highlighter: rouge
input: GFM

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
